# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bae909bac1dc1e367e66f7f19102386f0f50cd9127d03d970ba0886370b840929032cc3435d7bfa765c08fed3bfd1c63451fe8dbf4c6feb95ece12f0b054cb24

test:
  secret_key_base: dde5d7760c9664bd936070d9631b0d0fb296a63ba33ca5a96b8828999fdcc036e608f0cff7d57c7c7a38757d45a1e69bacb88a945ae518f7495403cecc0ec390

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
